title: Aprendiendo git y github
author: Marina Nieto
email: mandieto@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
  
  Descripción modelo de la web que estamos armando con github lab
  para poder practicar armar una web con github pages.
  Para más info, mandame un e-mail.

# social links
twitter_username: marinieto # DO NOT include the @ character, or else the build will fail!
github_username:  marandnie # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
